In [2]:
import numpy as np

# 1. Creating an array with values ranging from 0 to 9
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2. Reshaping the array to a 2x5 matrix
arr2 = arr1.reshape(2, 5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
# 3. Generating an array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
