In [2]:
import numpy as np

# 1. Creating an array with values ranging from 0 to 9
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 2. Reshaping the array to a 2x5 matrix
arr2 = arr1.reshape(2, 5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [5]:
# 3. Generating an array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 4. Generating an array of ones with shape (2, 2)
ones_array = np.ones((2, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]]


In [7]:
# 5. Creating an identity matrix of size 4x4
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
# 6. Computing the mean of all elements in an array
mean_value = np.mean(arr2)
print(mean_value)

4.5


In [9]:
# 7. Finding the maximum value in an array
max_value = np.max(arr2)
print(max_value)

9


In [10]:
# 8. Transposing a matrix
transposed_matrix = np.transpose(arr2)
print(transposed_matrix)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [11]:
# 9. Element-wise addition of two arrays
sum_array = arr2 + arr2
print(sum_array)

[[ 0  2  4  6  8]
 [10 12 14 16 18]]


In [12]:
# 10. Element-wise multiplication of two arrays
product_array = arr2 * arr2
print(product_array)

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [13]:
dot_product = np.dot(arr2,transposed_matrix)
print(dot_product)

[[ 30  80]
 [ 80 255]]


In [14]:
# 12. Finding unique elements in an array
unique_elements = np.unique(arr1)
print(unique_elements)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# 13. Calculating the standard deviation of an array
std_deviation = np.std(arr2)
print(std_deviation)

2.8722813232690143


In [16]:
# 14. Reshaping and flattening an array
flattened_array=arr2.flatten()
print(flattened_array)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# 15. Concatenating two arrays along a specified axis
concatenated_array = np.concatenate((arr2, transposed_matrix.reshape(2, 5)), axis=1)
print(concatenated_array)

[[0 1 2 3 4 0 5 1 6 2]
 [5 6 7 8 9 7 3 8 4 9]]


In [22]:
# 16. Applying a sine function element-wise
sin_values = np.sin(arr1)
print(sin_values)


[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [23]:
# 17. Extracting elements that satisfy a given condition
filtered_elements = arr1[arr1 > 5]
print(filtered_elements)

[6 7 8 9]


In [24]:

# 18. Creating a random array of specified shape
random_array = np.random.rand(3, 3)
print(random_array)

[[0.94267847 0.54523393 0.14879497]
 [0.67762538 0.07643869 0.87629132]
 [0.18684851 0.90047144 0.56168055]]


In [25]:
# 19. Finding indices of non-zero elements in an array
nonzero_indices = np.nonzero(arr1)
print(nonzero_indices)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),)


In [26]:
# 20. Computing the element-wise absolute values of an array
absolute_values = np.abs(arr2)
print(absolute_values)

[[0 1 2 3 4]
 [5 6 7 8 9]]
